/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-hero': HomeHero;
    'home-brands': HomeBrand;
    'home-statement': HomeStatement;
    'home-gap': HomeGap;
    'home-keep-scrolling': HomeKeepScrolling;
    'home-success-stories': HomeSuccessStory;
    'home-services': HomeService;
    'home-faq': HomeFaq;
    'page-about': PageAbout;
    'page-services': PageService;
    'page-work': PageWork;
    'page-contact': PageContact;
    'page-thank-you': PageThankYou;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
    'home-brands': HomeBrandsSelect<false> | HomeBrandsSelect<true>;
    'home-statement': HomeStatementSelect<false> | HomeStatementSelect<true>;
    'home-gap': HomeGapSelect<false> | HomeGapSelect<true>;
    'home-keep-scrolling': HomeKeepScrollingSelect<false> | HomeKeepScrollingSelect<true>;
    'home-success-stories': HomeSuccessStoriesSelect<false> | HomeSuccessStoriesSelect<true>;
    'home-services': HomeServicesSelect<false> | HomeServicesSelect<true>;
    'home-faq': HomeFaqSelect<false> | HomeFaqSelect<true>;
    'page-about': PageAboutSelect<false> | PageAboutSelect<true>;
    'page-services': PageServicesSelect<false> | PageServicesSelect<true>;
    'page-work': PageWorkSelect<false> | PageWorkSelect<true>;
    'page-contact': PageContactSelect<false> | PageContactSelect<true>;
    'page-thank-you': PageThankYouSelect<false> | PageThankYouSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Every image and video on the site lives here. Upload a new file, then pick it from the relevant section (Home → Success Stories, Pages → About, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description used for accessibility.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Journal articles. Set “Published at” to list a post on /blog; leave it empty to keep it as a draft.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL of the article, e.g. “why-your-brand-is-not-your-logo”. Auto-filled from the title when left empty.
   */
  slug: string;
  /**
   * One or two lines shown on the /blog index and used as the share description when no SEO description is set.
   */
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  author?: string | null;
  /**
   * Leave empty to keep this post as a draft. Set to a past date/time to publish it on /blog.
   */
  publishedAt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional override for the browser tab / share title.
   */
  seoTitle?: string | null;
  /**
   * Optional override for the meta / share description.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  author?: T;
  publishedAt?: T;
  content?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Shared across every page: navigation, footer, brand name and contact details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Wordmark shown in the hero and header.
   */
  brandName: string;
  brandTagline?: string | null;
  copyright?: string | null;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerTalkLabel?: string | null;
  footerContactButtonLabel?: string | null;
  footerContactHref?: string | null;
  /**
   * Looping logo animation at the bottom of every page.
   */
  footerLogoVideo?: (number | null) | Media;
  studioDetailsLabel?: string | null;
  email?: string | null;
  locationLine1?: string | null;
  locationLine2?: string | null;
  socialsLabel?: string | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Canonical origin used for metadataBase, canonical URLs, sitemap and social share cards. No trailing slash.
   */
  siteUrl?: string | null;
  /**
   * Fallback <title> for pages without their own title (the home page uses this).
   */
  seoTitle?: string | null;
  /**
   * Fallback meta description, ~150–160 characters.
   */
  seoDescription?: string | null;
  seoKeywords?: string | null;
  /**
   * Used for Open Graph / Twitter cards site-wide. Upload a 1200×630 image; falls back to the built-in cover art.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Top hero section of the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: number;
  brand: string;
  /**
   * Line breaks are kept as shown.
   */
  headline: string;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Logo strip under the hero.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-brands".
 */
export interface HomeBrand {
  id: number;
  label?: string | null;
  brands?:
    | {
        logo?: (number | null) | Media;
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The big “10+” statement section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-statement".
 */
export interface HomeStatement {
  id: number;
  stat: string;
  statCaption?: string | null;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  bylineName?: string | null;
  bylineRole?: string | null;
  bylineInitials?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * “We close the gap” band with the gap image.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-gap".
 */
export interface HomeGap {
  id: number;
  phraseLeft?: string | null;
  phraseRight?: string | null;
  image?: (number | null) | Media;
  copy?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Circular “keep scrolling” divider text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-keep-scrolling".
 */
export interface HomeKeepScrolling {
  id: number;
  label: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Pinned-scroll case study section on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-success-stories".
 */
export interface HomeSuccessStory {
  id: number;
  label?: string | null;
  pagerTag?: string | null;
  /**
   * Ambient video behind the section intro.
   */
  video?: (number | null) | Media;
  projects?:
    | {
        title: string;
        description: string;
        stat: string;
        statCaption: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Service list — shared by the home page section and the Services page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-services".
 */
export interface HomeService {
  id: number;
  intro?: string | null;
  label?: string | null;
  services?:
    | {
        name: string;
        kicker?: string | null;
        description: string;
        subItems?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        imageLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Frequently asked questions on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-faq".
 */
export interface HomeFaq {
  id: number;
  label?: string | null;
  ctaHeading?: string | null;
  ctaButtonLabel?: string | null;
  ctaHref?: string | null;
  headline?: string | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content of the /about page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-about".
 */
export interface PageAbout {
  id: number;
  /**
   * Looping chrome video in the about hero.
   */
  heroVideo?: (number | null) | Media;
  heroTitle?: string | null;
  heroLede?: string | null;
  circularInner?: string | null;
  circularOuter?: string | null;
  storyTitle?: string | null;
  quoteLead?: string | null;
  storyParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  founderAvatar?: (number | null) | Media;
  founderName?: string | null;
  founderRole?: string | null;
  manifestoTitle?: string | null;
  manifestoCtaLabel?: string | null;
  manifestoCtaHref?: string | null;
  principles?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content of the /services page. The service list itself is shared — edit it under Home → Services.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-services".
 */
export interface PageService {
  id: number;
  /**
   * Looping chrome video in the services hero.
   */
  heroVideo?: (number | null) | Media;
  heroTitle?: string | null;
  heroLede?: string | null;
  finalCtaLines?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  finalCtaKicker?: string | null;
  finalCtaLabel?: string | null;
  finalCtaHref?: string | null;
  finalCtaImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content of the /work page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-work".
 */
export interface PageWork {
  id: number;
  heroTitle?: string | null;
  heroLede?: string | null;
  projectsLabel?: string | null;
  projects?:
    | {
        title: string;
        /**
         * Tick “highlight” to render a part in blue.
         */
        kickerParts?:
          | {
              text: string;
              highlight?: boolean | null;
              id?: string | null;
            }[]
          | null;
        intro?: string | null;
        body?: string | null;
        includes?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        caption?: string | null;
        image?: (number | null) | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  marqueeLine1?: string | null;
  /**
   * Tick “highlight” to render a part in blue.
   */
  marqueeLine2?:
    | {
        text: string;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  marqueeVideo?: (number | null) | Media;
  includesLabel?: string | null;
  readMoreLabel?: string | null;
  readLessLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content of the /contact-form page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact".
 */
export interface PageContact {
  id: number;
  introHeading?: string | null;
  /**
   * The email address inside this text is automatically turned into a mailto link.
   */
  introLede?: string | null;
  introEmail?: string | null;
  cardTitle?: string | null;
  cardDescription?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  labelName?: string | null;
  labelEmail?: string | null;
  labelPhone?: string | null;
  labelMessage?: string | null;
  submitLabel?: string | null;
  submittingLabel?: string | null;
  errorMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Confirmation shown after the contact form is submitted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-thank-you".
 */
export interface PageThankYou {
  id: number;
  heading?: string | null;
  sub?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandTagline?: T;
  copyright?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerTalkLabel?: T;
  footerContactButtonLabel?: T;
  footerContactHref?: T;
  footerLogoVideo?: T;
  studioDetailsLabel?: T;
  email?: T;
  locationLine1?: T;
  locationLine2?: T;
  socialsLabel?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  siteUrl?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoKeywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  brand?: T;
  headline?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-brands_select".
 */
export interface HomeBrandsSelect<T extends boolean = true> {
  label?: T;
  brands?:
    | T
    | {
        logo?: T;
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-statement_select".
 */
export interface HomeStatementSelect<T extends boolean = true> {
  stat?: T;
  statCaption?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  bylineName?: T;
  bylineRole?: T;
  bylineInitials?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-gap_select".
 */
export interface HomeGapSelect<T extends boolean = true> {
  phraseLeft?: T;
  phraseRight?: T;
  image?: T;
  copy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-keep-scrolling_select".
 */
export interface HomeKeepScrollingSelect<T extends boolean = true> {
  label?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-success-stories_select".
 */
export interface HomeSuccessStoriesSelect<T extends boolean = true> {
  label?: T;
  pagerTag?: T;
  video?: T;
  projects?:
    | T
    | {
        title?: T;
        description?: T;
        stat?: T;
        statCaption?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-services_select".
 */
export interface HomeServicesSelect<T extends boolean = true> {
  intro?: T;
  label?: T;
  services?:
    | T
    | {
        name?: T;
        kicker?: T;
        description?: T;
        subItems?:
          | T
          | {
              value?: T;
              id?: T;
            };
        image?: T;
        imageLabel?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-faq_select".
 */
export interface HomeFaqSelect<T extends boolean = true> {
  label?: T;
  ctaHeading?: T;
  ctaButtonLabel?: T;
  ctaHref?: T;
  headline?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-about_select".
 */
export interface PageAboutSelect<T extends boolean = true> {
  heroVideo?: T;
  heroTitle?: T;
  heroLede?: T;
  circularInner?: T;
  circularOuter?: T;
  storyTitle?: T;
  quoteLead?: T;
  storyParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  founderAvatar?: T;
  founderName?: T;
  founderRole?: T;
  manifestoTitle?: T;
  manifestoCtaLabel?: T;
  manifestoCtaHref?: T;
  principles?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-services_select".
 */
export interface PageServicesSelect<T extends boolean = true> {
  heroVideo?: T;
  heroTitle?: T;
  heroLede?: T;
  finalCtaLines?:
    | T
    | {
        text?: T;
        id?: T;
      };
  finalCtaKicker?: T;
  finalCtaLabel?: T;
  finalCtaHref?: T;
  finalCtaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-work_select".
 */
export interface PageWorkSelect<T extends boolean = true> {
  heroTitle?: T;
  heroLede?: T;
  projectsLabel?: T;
  projects?:
    | T
    | {
        title?: T;
        kickerParts?:
          | T
          | {
              text?: T;
              highlight?: T;
              id?: T;
            };
        intro?: T;
        body?: T;
        includes?:
          | T
          | {
              value?: T;
              id?: T;
            };
        caption?: T;
        image?: T;
        alt?: T;
        id?: T;
      };
  marqueeLine1?: T;
  marqueeLine2?:
    | T
    | {
        text?: T;
        highlight?: T;
        id?: T;
      };
  marqueeVideo?: T;
  includesLabel?: T;
  readMoreLabel?: T;
  readLessLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact_select".
 */
export interface PageContactSelect<T extends boolean = true> {
  introHeading?: T;
  introLede?: T;
  introEmail?: T;
  cardTitle?: T;
  cardDescription?: T;
  email?: T;
  phone?: T;
  address?: T;
  labelName?: T;
  labelEmail?: T;
  labelPhone?: T;
  labelMessage?: T;
  submitLabel?: T;
  submittingLabel?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-thank-you_select".
 */
export interface PageThankYouSelect<T extends boolean = true> {
  heading?: T;
  sub?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}